### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by cwacek** [rhettg/dmc#5]
pip install doesn't work because of missing README.md.

```
(env)example@example:~/tapio_agent/test$ pip install dmc
Downloading/unpacking dmc
  Downloading dmc-0.0.1.tar.gz
  Running setup.py (path:/home/example/env/build/dmc/setup.py) egg_info for package dmc
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/example/env/build/dmc/setup.py", line 25, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/example/env/build/dmc/setup.py", line 25, in <module>

    long_description=open('README.md').read(),

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/example/env/build/dmc
Storing debug log for failure in /home/example/.pip/pip.log
```

**Comment by themiurgo** [comment]
Could you fix this, please?

**Comment by kevinleestone** [comment]
Using setuptools fixes this #8
